### ISSUE TITLE
Set min video.scale

### ISSUE THREAD

**Issue by Bastard007** [jpikl/cfxnes#11]
How to set the minimum video.scale value?
For example, I do not need a value of 1, only 2, 3, and 4.

Thank you.

**Comment by jpikl** [comment]
There is no API for that. You can simply check the value you are going to set as video.scale.

Let's say you have a button to decrease video.scale value. Then it's onclick implementation could be:

```
const MIN_VIDEO_SCALE = 2;

button.onClick = () => {
    if (nes.video.scale > MIN_VIDEO_SCALE) {
        nes.video.scale--;
    }
};
```
