### ISSUE TITLE
error in examples

### ISSUE THREAD

**Issue by AdriaSaz** [jpikl/cfxnes#13]
Hi I do not understand how this works, because if you run the examples there are error

**Comment by jpikl** [comment]
Hi. You will have to explain in more detail how did you run the examples and exactly what error it gave you.

The easiest way to run the examples is to put the HTML files together with cfxnes.js into one directory and serve them as static web pages using an HTTP server. For that i would recommend the `http-server` npm package. Just install it using `npm -g i http-server`, then run it with `http-server` command, the open http://127.0.0.1:8080 in your browser.

**Comment by AdriaSaz** [comment]
I can´t run this without http-server npm? in a normal webserver apache or xampp? 

ok thanks

**Comment by jpikl** [comment]
You can use whathever http server you want. That was just an example.

**Comment by AdriaSaz** [comment]
Then I put the html of the example together to cfxnes.js only those 2 files? and the rom of course

I Try

**Comment by AdriaSaz** [comment]
I put in the same folder:
Folders

Audio
Input
Properties
rom
system
video


Files
.eslintrc.js
cfxnes.js
index.html(minimal example file)
mario.nes ( rom)

Only load page they has a js error :

Uncaught SyntaxError: Unexpected token {        (index):10 
Uncaught TypeError: cfxnes is not a function    at (index):10



I'm use xampp with php 5. but this emulator it's full js, no?

**Comment by AdriaSaz** [comment]
the same problem with advanced example file

**Comment by jpikl** [comment]
I see the problem now.

You are using the original source code, not the built library.
Run `npm run build` in `lib` directory. The `cfxnes.js` you should be using is in the `dist` directory.

**Comment by AdriaSaz** [comment]
I'm sorry or I'm very noob or I don't understand this

1- Install node.js on windows
1open the nodejs command console
3- I went to the lib directory
4 I did an npm install, dependencies were installed
5- When doing npm run build tell me this, do I need java in the directory?


> cfxnes-lib@0.7.0 build C:\Users\bitman\Downloads\cfxnes-master\cfxnes-master\lib
> node build.js

java -jar C:\Users\bitman\Downloads\cfxnes-master\cfxnes-master\lib\node_modules\google-closure-compiler\compiler.jar --compilation_level=ADVANCED --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --create_source_map=%outname%.map --source_map_location_mapping=../core|../../core --source_map_location_mapping=src|../src --module_resolution=NODE --dependency_mode=STRICT --rewrite_polyfills=false --output_wrapper_file=umd.template --assume_function_wrapper=true --formatting=SINGLE_QUOTES --externs=externs.js --entry_point=src/cfxnes --js=..\core\src\**js --js=..\core\index.js --js=src\**js --js=!..\core\src\.eslintrc.js --js=!src\.eslintrc.js --js_output_file=dist\cfxnes.js

Process spawn error. Is java in the path?
spawn java ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cfxnes-lib@0.7.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cfxnes-lib@0.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bitman\AppData\Roaming\npm-cache\_logs\2019-08-23T20_35_21_352Z-debug.log
[2019-08-23T20_35_21_352Z-debug.log](https://github.com/jpikl/cfxnes/files/3536117/2019-08-23T20_35_21_352Z-debug.log)

**Comment by AdriaSaz** [comment]
don't have a tutorial for noobs?? hehe or a emulator builded download

**Comment by jpikl** [comment]
Yes, I am using closure compiler which requires Java.

I've just realized that there is a much easier way. Just download the latest [release](https://github.com/jpikl/cfxnes/releases/download/v0.7.0/cfxnes-0.7.0.zip) which contains `lib/cfxnes.js` you need.

**Comment by AdriaSaz** [comment]
Thanx Works perfectly
