### ISSUE TITLE
Save and load ?

### ISSUE THREAD

**Issue by yasaricli** [jpikl/cfxnes#2]
How can I save the game ?

```JS
nes = new CFxNES({});

nes.downloadCartridge(url).then(function() {
  nes.start();
});

// save and re load ?

```

**Comment by jpikl** [comment]
It depends what you mean by saving the game.

1. The are games that support saving using battery-backed RAM (e.g. The Legend of Zelda). This memory can be accessed through `nes.nvram` property which is an `Uint8Array` that you can read or write to. You will have to use newer version of API (see [documentation](https://github.com/jpikl/cfxnes/blob/master/lib/API.md))

2. Saving and restoring state of emulator is currently not implemented but it's planned feature.
