### ISSUE TITLE
How can i setup Joypad as default alternate input?

### ISSUE THREAD

**Issue by Mangaclub** [jpikl/cfxnes#20]
Hi there,

is there any way i can tell the emulator to use the joypad by default and the keyboard as alternative? 
The examples sadly just show how to plugit in a webpage but not how to configure the default keys.

**Comment by jpikl** [comment]
Hi, there are more examples in API documentation.

- [init options](https://github.com/jpikl/cfxnes/blob/master/lib/API.md#cfxnesoptions)
- [nes.inputs](https://github.com/jpikl/cfxnes/blob/master/lib/API.md#nesinputs)

**Comment by Mangaclub** [comment]
thanks! so i added  inputs: {
    '1.joypad.a': 'keyboard.x',
    '1.joypad.b': ['keyboard.y', 'keyboard.z'],
    '1.joypad.start': 'joypad.start',
    '1.joypad.select': 'keyboard.shift',
    '1.joypad.up': 'keyboard.up',
    '1.joypad.down': 'keyboard.down',
    '1.joypad.left': 'keyboard.left',
    '1.joypad.right': 'keyboard.right',
    '2.zapper.trigger': 'mouse.left',
  },
but that doesnt work, also i tryed gamepad.start or just start for the start button but that does not work either.
What would be the correct declaration?

**Comment by Mangaclub** [comment]
thanks, i should read this more carefully
