### ISSUE TITLE
how can I put this library on a netlify website so i can run nes games?

### ISSUE THREAD

**Issue by MrSnailman** [jpikl/cfxnes#21]
how can I put this library on a netlify website so i can run nes games? Ive been trying to figure it out for a while had no luck

**Comment by jpikl** [comment]
Here is a [minimal example](https://github.com/jpikl/cfxnes/tree/master/lib#example) which you can deploy together with the library. You can get the `cfxnes.js` from the [latest release](https://github.com/jpikl/cfxnes/releases)

**Comment by MrSnailman** [comment]
Lol im stupid I made it more complicated than it had to be thank you.

**Comment by MrSnailman** [comment]
> Here is a [minimal example](https://github.com/jpikl/cfxnes/tree/master/lib#example) which you can deploy together with the library. You can get the `cfxnes.js` from the [latest release](https://github.com/jpikl/cfxnes/releases)

how do i make it save data im not sure what to do with the uint8array thingy
