### ISSUE TITLE
compile lib 

### ISSUE THREAD

**Issue by pengqin** [jpikl/cfxnes#3]
when I want compile lib  use command  "node build.js"
some error happend 
 ERROR - required "module$__$core$src$common" namespace never provided

**Comment by jpikl** [comment]
This looks like a closure compiler issue. I tried the compilation on Linux and it works fine, but on Windows I am getting the same error as you. With newer closure compiler version (20170626.0.0), it fails even on Linux.

I will report this to the closure compiler project. In the meantime, I could try downgrading closure compiler to see if it helps.

What OS are you using, by the way?

**Comment by jpikl** [comment]
It's fixed.

The problem was actually caused by wrong path separator used in build.js. Closure compiler requires backslashes on Windows.

**Comment by pengqin** [comment]
I‘m using windows 10.
it's work , thanks you.
