### ISSUE TITLE
Virtual joystick

### ISSUE THREAD

**Issue by pengqin** [jpikl/cfxnes#5]
The api can use  js to trigger  input event？
beacuse I want  use Virtual joystick to play

**Comment by jpikl** [comment]
You can use `nes.input.state` module to change state of NES controllers (wheter a button is pressed or not), as described [here](https://github.com/jpikl/cfxnes/blob/master/lib/API.md#nesinputs).

`nes.inputs.state.set('1.joypad.a', true); // Button A of the 1st controller is now pressed`

**Comment by pengqin** [comment]
thanks for your help
