### ISSUE TITLE
how to start ROM when the page is loaded?

### ISSUE THREAD

**Issue by Bastard007** [jpikl/cfxnes#6]
How to start ROM by default when loading a page?

**Comment by jpikl** [comment]
I am not sure if this is what you had in mind:

`nes.rom.load(source).then(() => nes.start())`

This will load and then start a ROM. See [API docs](https://github.com/jpikl/cfxnes/blob/master/lib/API.md#nesrom) for more details.

**Comment by Bastard007** [comment]
Sorry for my bad english...

I put the code in header:

```
 <script src="libs.js"></script>
 <script src="cfxnes.js"></script>
 <script src="app.js"></script>
```

and in the body

```
<nav riot-tag="app-nav"></nav>
<main riot-tag="app-main"></main>
```
What code should be inserted, what would be loaded ROM when loading the page?

**Comment by jpikl** [comment]
It seem like you are trying to reuse pieces of code from the the cfxnes app. That is not necessary, you can just use the library on its own. There are [some examples](https://github.com/jpikl/cfxnes/tree/master/lib/examples) that might help.

**Comment by Bastard007** [comment]
Thank you. Everything working!!!!
