### ISSUE TITLE
quick sound in some games and clicks

### ISSUE THREAD

**Issue by Bastard007** [jpikl/cfxnes#8]
For example In the game SuperMario - the sound of music is fast, sometimes cheeks are audible.

Is there a sound parameter in the API, which that is responsible for the play sound speed in the API?

Sorry, my English very bad.

**Comment by jpikl** [comment]
Some game were made for PAL region and they should run at 50FPS instead of 60FPS (NTSC). The auto detection is not very reliable at the moment, but you can set the region manually `nes.region = 'pal'`.

**Comment by Bastard007** [comment]
Thank you
